### ISSUE TITLE
API test suite: 128 stale tests — same drift class as CLI cleanup

### ISSUE THREAD

**Issue by sseshachala** [sseshachala/conductai#987]
## Context

Surfaced during #985 fix verification on 2026-07-25. CI run 30170557291 shows **128 API tests failing / 502 passing** across 26 files. None of the failures were caused by the #985 fix — they're all pre-existing drift accumulated over time.

Same pattern we hit and fixed in `conduct-cli` earlier today (that pass fixed 33 tests, took ~1-2 hours). API surface is larger.

## Failure categories

| Pattern | Count | Root cause |
|---|---|---|
| `AttributeError: Mock object has no attribute 'id' / 'workspace_id' / 'current_version_id'` | 31 | `MagicMock()` used for DB rows; production code now accesses attributes the mocks don't spec |
| `assert 422 == 200/201/401/404` | 20 | Endpoints return 422 (validation) where tests expected the old happy path — request body schema tightened |
| `AssertionError: {"detail":[{"loc":["query","args"]...}]}` | 9 | `Depends(require_permission)` override pattern doesn't match FastAPI's contract; TestClient calls the override as if it were a query-param dep |
| `StopIteration` | 11 | Mock iterators exhausted or setup returns wrong shape |
| `KeyError: 'app.models.run_analytics_event'` | 6 | Model was renamed / removed; tests still reference the old name |
| `TypeError: '_ModelStub' object is not callable` | 5 | Test uses a stubbed model class that's now instantiated differently in prod |
| `TypeError: get_workspace_id() got an unexpected keyword argument 'x_api_key'` | 4 | Auth dependency signature changed |
| `WorkflowValidationError: extends: not supported for community submissions` | 3 | Playbook validator rule tightened |
| **Missing files** | 6 | 3× `packages/conduct-cli/src/conduct_cli/hook_template.py` (moved), 3× `apps/api/playbooks/ai_ready.yaml` (removed/renamed) |
| Other (assertion drift, one-offs) | ~33 | Various small drift |

## Top hitters by file

```
16  tests/test_workflow_crud.py         # mock attribute drift + response codes
14  tests/test_analytics_dora.py         # DORA metric endpoint shape changes
12  tests/test_z_executor_lifecycle.py   # executor return shape drift
10  tests/test_session_reports.py        # report generator signature drift
 8  tests/test_team_os.py
 8  tests/test_eval_harness.py
 7  tests/test_guard_events_api.py
 6  tests/test_guard_policy_engine.py
 5  tests/test_online_scorer.py
 4  tests/test_token_paths.py
 4  tests/test_telemetry.py
 4  tests/test_guard_spend_month_window.py
 4  tests/test_agent_memory_vector.py
 3  tests/test_webhook_e2e.py
 3  tests/test_phase2_integration_contracts.py
 3  tests/test_autopilot_playbook.py
 3  tests/test_ai_ready_playbook.py
 3  tests/guard/test_hook_signed_policy.py
```

Plus ~10 files with 1-2 failures each.

## Suggested fix order (cheapest wins first)

1. **Missing files (6 failures)** — grep for the moved/renamed paths, update test imports/paths.
2. **Response-code drift (20 failures)** — for each `assert 422 == X`, run the request manually, verify the current expected code, update the test.
3. **Mock attribute drift (31 failures)** — extend the shared mock fixtures (or use `spec=Model` on MagicMock) so accesses like `.workspace_id` work.
4. **FastAPI dep-override pattern (9 failures)** — fix the `require_permission` override pattern once in a shared conftest.py helper, apply everywhere.
5. **Model/schema drift (14 failures: KeyError, ModelStub, signature)** — targeted per-file cleanup.
6. **Remainder (~48)** — case-by-case.

## Effort estimate

~4-6 hours end-to-end if approached systematically per category. Can be delegated to a subagent for the mechanical passes (categories 1-3), with human review on 4-6 where the fix may involve real behavior questions.

## Related

- CLI cleanup pass (same pattern, smaller scope): see commits `be602bf`, `9e089c3` on main from 2026-07-25
- CI blocked by `test_guard.py:372` (max_overflow on SQLite) — currently ignored via `--ignore=tests/test_guard.py` in `ci.yml`; that file needs its own fix pass separately
- Also blocked by `-x` removal (bailing at first failure hid the aggregate): reverted in commit `55cb0f2`

## Non-goals for this issue

Do NOT re-file per-test issues. This aggregate is the one place we track the drift class. Individual PR passes can reference `Refs #<this-issue>`.
